#!/bin/bash
#PBS -l nodes=1:ppn=16:dc2,walltime=01:00:00
#PBS -N app-AFQ_figures
#PBS -V

if [ $ENV == "IUHPC" ]; then
	cd $PBS_O_WORKDIR
	module load matlab
fi

export MATLABPATH=$MATLABPATH:$SERVICE_DIR
#matlab -nodisplay -nosplash -r main
matlab -nodesktop -nosplash -r main
count=$(ls images/*.png | wc -l)
if [ $count -eq 20 ];
then 
  echo 0 > finished
else
  echo "images missing"
  echo 1 > finished
  exit 1
fi
